# imports

In [3]:
from raqun.utils.maths import *

In [5]:
print(log_t(5))

counts = {'00': 524, '01': 200, '10': 112, '11': 112}

probsArr = probs(counts, 4)

dists = dist(probsArr)

print(dists)

(5, 3)
[1.10497238 2.         4.         4.        ]


In [11]:
from raqun.utils.qun import *

ctrl = ctrlGen(5, 3)
print(ctrl)

mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
mat = np.array(mat)
paddedMat = padder(mat)
print(paddedMat)

['000' '001' '010' '011' '100']
[[1 2 3 0]
 [4 5 6 0]
 [7 8 9 0]
 [0 0 0 0]]
